groups:
  - name: ec2-worker-autoscaling
    rules:
      - alert: HighAverageNodeCpuUsage
        expr: |
          avg(
            100 - (
              avg by (instance) (
                rate(node_cpu_seconds_total{job="node-exporter-ec2-workers", mode="idle"}[2m])
              ) * 100
            )
          ) > 70
        for: 2m
        labels:
          severity: warning
          action: scale-ec2
        annotations:
          summary: "High average EC2 worker CPU usage"
          description: "Average CPU usage across EC2 worker nodes is above 70% for 2 minutes."

      - alert: LowAverageNodeCpuUsage
        expr: |
          avg(
            100 - (
              avg by (instance) (
                rate(node_cpu_seconds_total{job="node-exporter-ec2-workers", mode="idle"}[5m])
              ) * 100
            )
          ) < 30
        for: 5m
        labels:
          severity: warning
          action: scale-down-ec2
        annotations:
          summary: "Low average EC2 worker CPU usage"
          description: "Average CPU usage across EC2 worker nodes is below 30% for 5 minutes."
