global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alert_rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "54.163.216.25:9093"

scrape_configs:
  # Monitor the main monitoring/server host.
  - job_name: "node-exporter-monitor-host"
    static_configs:
      - targets:
          - "54.163.216.25:9100"
        labels:
          role: "monitor"
          group: "monitor"
          instance_name: "server-monitor"

  # Automatically monitor EC2 worker nodes using AWS EC2 Service Discovery.
  # Terraform worker nodes must have the tag: Monitoring=enabled.
  - job_name: "node-exporter-ec2-workers"
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
        refresh_interval: 30s

    relabel_configs:
      # Keep only EC2 instances with Monitoring=enabled.
      - source_labels: [__meta_ec2_tag_Monitoring]
        regex: enabled
        action: keep

      # Keep only running EC2 instances.
      - source_labels: [__meta_ec2_instance_state]
        regex: running
        action: keep

      # Use the private IP address to scrape node_exporter.
      - source_labels: [__meta_ec2_private_ip]
        target_label: __address__
        replacement: "${1}:9100"

      # Add useful labels for easier filtering in Prometheus/Grafana.
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance_name

      - source_labels: [__meta_ec2_instance_id]
        target_label: instance_id

      - source_labels: [__meta_ec2_private_ip]
        target_label: private_ip

      - source_labels: [__meta_ec2_public_ip]
        target_label: public_ip

      - source_labels: [__meta_ec2_availability_zone]
        target_label: availability_zone

      # Mark these targets as scalable worker nodes.
      - target_label: role
        replacement: worker

      - target_label: group
        replacement: workers