apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hospital-traefik-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kien-devops/cicd-ecr-kube-ec2-gitaction.git
    targetRevision: devops1
    path: k8s-traefik-lb-demo/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: hospital
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

