# Create a dedicated namespace for the Traefik controller.
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
# Create a dedicated namespace for the hospital application.
apiVersion: v1
kind: Namespace
metadata:
  name: hospital
