# Chay frontend hospital app tu ECR image.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment-v1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe-v1
  template:
    metadata:
      labels:
        app: fe-v1
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: fe-v1
          image: 545587707922.dkr.ecr.ap-southeast-1.amazonaws.com/ecr-fe:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
