# Chay backend hospital API tu ECR image.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-deployment-v1
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: be-v1
  template:
    metadata:
      labels:
        app: be-v1
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: be-v1
          image: 545587707922.dkr.ecr.ap-southeast-1.amazonaws.com/ecr-be:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
